name: PKUAutoSubmit

on:
  schedule:
<<<<<<< HEAD
    - cron: '22 6 * * *'
=======
    - cron: '0 1 * * 1,2,4,5'
>>>>>>> cc87cee2b8412ff5f103b1691897eb12dc9262aa
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: 'Install requirements'
        run: 
          pip install selenium
        
      - name: 'Working'
        run:
          python main.py --ID ${{secrets.ID}} --PASSWORD ${{secrets.PASSWORD}} --MAIL_ADDRESS ${{secrets.MAIL_ADDRESS}} --PHONE_NUMBER ${{secrets.PHONE_NUMBER}} --SENDKEY ${{secrets.SENDKEY}}
          

